[package]
name = "optimizeme"
version = "0.1.0"
authors = ["root <nathen@devops.worker.htb>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num-bigint = "0.4.0"

